[libraries]
apache-commons-collections = { group = 'org.apache.commons', name = 'commons-collections4', version = '4.6.0' }
assertJ = { group = 'org.assertj', name = 'assertj-core', version = '3.27.7' }
guava = { group = 'com.google.guava', name = 'guava', version = '33.7.2-jre' }

[versions]
junit = '4.13.2'