[versions]
android-gradle = '9.1.0-alpha08'
java = '21'

[libraries]
agrona = { group = 'org.agrona', name = 'agrona', version = '2.6.1' }
android-activity = { group = 'androidx.activity', name = 'activity', version = '1.13.0' }
android-constraintLayout = { group = 'androidx.constraintlayout', name = 'constraintlayout', version = '2.2.2' }
android-espresso-intents = { group = 'androidx.test.espresso', name = 'espresso-intents', version = '3.7.0' }
android-material = { group = 'com.google.android.material', name = 'material', version = '1.14.0' }
android-test = { group = 'androidx.test', name = 'core', version = '1.7.0' }
assertJ = { group = 'org.assertj', name = 'assertj-core', version = '3.27.7' }
jUnit4 = { group = 'junit', name = 'junit', version = '4.13.2' }
robolectric = { group = 'org.robolectric', name = 'robolectric', version = '4.16.1' }

[plugins]
android-application = { id = 'com.android.application', version.ref = 'android-gradle' }